### ISSUE TITLE
IndexOutOfRange exception when reading .mobi file

### ISSUE THREAD

**Issue by theweavrs** [hartalex/mobireader#1]
This is the mobi file. [Google Drive Link](https://drive.google.com/open?id=0ByANaPI_IXncVVFhYXFSbVg3NjA)

To reproduce:
Just open the file as usual.

Build Info:
Built directly from source code.

Thanks for this great reader, it does work on some books but fails on this and one other book. Would appreciate any help!

Keep it up.

**Comment by hartalex** [comment]
Thanks the example file helped a lot.

I've made some changes and it should work with this file now.

**Comment by theweavrs** [comment]
I will give it a try and report.

**Comment by theweavrs** [comment]
@hartalex this issue is now fixed and other formatting problems are fixed too. There is another file that is having problems, I will create an issue with full details and a copy of the eBook.
