### ISSUE TITLE
Any way to retrieve images from mobi ebook (cover image)?

### ISSUE THREAD

**Issue by theweavrs** [hartalex/mobireader#3]
Ability to retrieve images would complete the reader. I think it must be in the EXTH Header but I could be wrong.

Reference: [This is how Calibre Parses Mobi](https://github.com/kovidgoyal/calibre/tree/master/src/calibre/ebooks/mobi/reader). The code is in `Python` but it is understandable and essential parts can be ported.

**Comment by hartalex** [comment]
Sure but as this a console application there is no need to pull out any pictures.

**Comment by theweavrs** [comment]
@hartalex I don't see why it won't be used in a GUI Application. We could make this a portable library even. There is currently no Open-source Mobi Reader written in C# or any library that deals with it correctly. Furthermore, as a library it will be more appealing and hence will attract more contributors.

I, myself, am creating an eBook reader for UWP 10 and in need of such a reader and I think ability to retrieve images (as an option of course) would be very good.

Of course, it is your call. :)

**Comment by hartalex** [comment]
I don't have a whole lot of time to dedicate to making it a portable library.
If you do have the time that would be awesome

Here are some of the file spec references I used
https://wiki.mobileread.com/wiki/Mobi
https://wiki.mobileread.com/wiki/PalmDOC
